# Generated by Django 3.2.7 on 2021-10-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aperture',
            field=models.CharField(blank=True, max_length=10, verbose_name='Aperture'),
        ),
    ]
