# Generated by Django 3.2.7 on 2021-10-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211004_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='picture',
            field=models.ImageField(upload_to='static/img/home', verbose_name='Your Photo'),
        ),
    ]
