# Generated by Django 3.2.7 on 2021-10-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_skills_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_img',
            field=models.ImageField(upload_to='img/home/', verbose_name='Your profile photo'),
        ),
        migrations.AlterField(
            model_name='home',
            name='picture',
            field=models.ImageField(upload_to='img/home/', verbose_name='Your Photo'),
        ),
    ]
