# Generated by Django 3.2.7 on 2021-10-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211004_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='picture',
            field=models.ImageField(upload_to='home/', verbose_name='Your Photo'),
        ),
    ]
