# Generated by Django 3.2.7 on 2021-10-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_home_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_img',
            field=models.ImageField(upload_to='home/', verbose_name='Your profile photo'),
        ),
    ]
